# The project language
language: c

os:
  - osx
  - linux

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libssl-dev

script:
  - make
  - make -C librhash test
  - librhash/test_hashes --flags
  - make test
