# The project language
language: c
sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - ADDCFLAGS="-DOPENSSL_RUNTIME -rdynamic"
        - ADDLDFLAGS="-ldl"
    - os: osx
      osx_image: xcode6.4
      compiler: clang
      env:
        - ADDCFLAGS=
        - ADDLDFLAGS=
    - os: osx
      compiler: clang
      env:
        - ADDCFLAGS="-DOPENSSL_RUNTIME -I/usr/local/opt/openssl/include"
        - ADDLDFLAGS=

addons:
  apt:
    packages:
      - libssl-dev

script:
  - make ADDCFLAGS="$ADDCFLAGS" ADDLDFLAGS="$ADDLDFLAGS"
  - make -C librhash test ADDCFLAGS="$ADDCFLAGS" ADDLDFLAGS="$ADDLDFLAGS"
  - librhash/test_hashes --flags
  - make test
