# The project language
language: c

matrix:
  include:
    - name: "linux shared debug ssl-runtime"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: false
      env:
        - CONFIGURE_FLAGS="--disable-static --enable-openssl=runtime --enable-debug"
      addons:
        apt:
          packages:
            - libssl-dev

    - name: "linux static"
      os: linux
      compiler: gcc
      sudo: false
      env:
        - CONFIGURE_FLAGS="--enable-static --disable-openssl"

    - name: "xcode-6.4 static"
      os: osx
      osx_image: xcode6.4
      compiler: clang
      sudo: false
      env:
        - CONFIGURE_FLAGS="--enable-static --disable-openssl"

    - name: "xcode-7.3 static ssl"
      os: osx
      osx_image: xcode7.3
      compiler: clang
      sudo: false
      env:
        - CONFIGURE_FLAGS="--enable-static --enable-openssl --extra-cflags=-I/usr/local/opt/openssl/include --extra-ldflags=-L/usr/local/opt/openssl/lib"

    - name: "xcode-def shared ssl"
      os: osx
      compiler: clang
      sudo: false
      env:
        - CONFIGURE_FLAGS="--disable-static --enable-openssl --extra-cflags=-I/usr/local/opt/openssl/include --extra-ldflags=-L/usr/local/opt/openssl/lib"

    - name: "xcode-12 shared debug ssl-runtime"
      os: osx
      osx_image: xcode12
      compiler: clang
      sudo: false
      env:
        - CONFIGURE_FLAGS="--disable-static --enable-debug --enable-openssl=runtime --extra-cflags=-I/usr/local/opt/openssl/include"

    - name: "arm-linux static"
      os: linux
      compiler: arm-linux-gnueabi-gcc
      sudo: required # enable FS with binfmt support
      env:
        - CONFIGURE_FLAGS="--enable-static --disable-openssl --disable-gettext"
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi libc-dev-armel-cross
            - qemu qemu-user-static binfmt-support

    - name: "ppc-linux static"
      os: linux
      compiler: powerpc-linux-gnu-gcc
      sudo: required
      env:
        - CONFIGURE_FLAGS="--enable-static --disable-openssl --disable-gettext"
      addons:
        apt:
          packages:
            - gcc-powerpc-linux-gnu libc-dev-powerpc-cross
            - qemu qemu-user-static binfmt-support

    - name: "ppc64-linux static"
      os: linux
      compiler: powerpc64-linux-gnu-gcc
      sudo: required
      env:
        - CONFIGURE_FLAGS="--enable-static --disable-openssl --disable-gettext"
      addons:
        apt:
          sources:
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe'
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ xenial-updates main universe'
          packages:
            - gcc-powerpc64-linux-gnu libc-dev-ppc64-cross
            - qemu qemu-user-static binfmt-support

    - name: "mips64el-linux static"
      os: linux
      compiler: mips64el-linux-gnuabi64-gcc
      sudo: required
      env:
        - CONFIGURE_FLAGS="--enable-static --disable-openssl --disable-gettext"
      addons:
        apt:
          sources:
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe'
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ xenial-updates main universe'
          packages:
            - gcc-mips64el-linux-gnuabi64 libc-dev-mips64el-cross
            - qemu qemu-user-static binfmt-support

    - name: "mingw64 static"
      os: linux
      compiler: i686-w64-mingw32-gcc
      sudo: false
      env:
        - CONFIGURE_FLAGS="--target=i686-w64-mingw32 --enable-static --enable-lib-shared --disable-openssl --disable-gettext"
      addons:
        apt:
          packages:
            - dpkg gcc-mingw-w64-i686 wine1.6-i386
      script:
        - cd rhash
        - ./configure --sysconfdir=/etc $CONFIGURE_FLAGS
        - make || ! cat config.mak librhash/config.mak config.log
        - make -C librhash test_static.exe && wine librhash/test_static.exe --info
        - wine librhash/test_static.exe
        - make install DESTDIR=$PWD/results
        - /usr/bin/find results/ -exec ls -ld '{}' ';'

    - name: "mingw32 static"
      os: linux
      compiler: x86_64-w64-mingw32-gcc
      sudo: false
      env:
        - CONFIGURE_FLAGS="--target=x86_64-w64-mingw32 --enable-static --enable-lib-shared --disable-openssl --disable-gettext"
      script:
        - cd rhash
        - ./configure --sysconfdir=/etc $CONFIGURE_FLAGS
        - make || ! cat config.mak librhash/config.mak config.log
        - make -C librhash test_static.exe && wine librhash/test_static.exe --info
        - wine librhash/test_static.exe
      addons:
        apt:
          packages:
            - dpkg gcc-mingw-w64-x86-64 wine1.6-amd64

script:
  - cd rhash
  - ./configure --sysconfdir=/etc $CONFIGURE_FLAGS
  - make
  - test -f ./rhash || cat config.mak librhash/config.mak config.log
  - make -C librhash print-info test
  - make test
