# The project language
language: c

matrix:
  include:
    - name: "Bindings: Java"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: false
      addons:
        apt:
          packages:
            - default-jdk junit4 default-jdk-doc
      script:
        - ./configure
        - make lib-shared test-lib print-info || ! cat config.mak librhash/config.mak config.log
        - javac --version && javadoc --version
        - make -C bindings build-java LIBRHASH_INC=-I$(pwd)/librhash LIBRHASH_LD=-L$(pwd)/librhash
        - LD_LIBRARY_PATH=$(pwd)/librhash make -C bindings test-java
        - make -C bindings clean-java

    - name: "Bindings: Mono"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: false
      addons:
        apt:
          packages:
            - cli-common-dev mono-devel monodoc-base
      script:
        - ./configure
        - make lib-shared test-lib print-info || ! cat config.mak librhash/config.mak config.log
        - mcs --version && mono --version
        - make -C bindings build-mono
        - LD_LIBRARY_PATH=$(pwd)/librhash make -C bindings test-mono
        - make -C bindings clean-mono

    - name: "Bindings: Perl"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: false
      script:
        - ./configure
        - make lib-shared test-lib print-info || ! cat config.mak librhash/config.mak config.log
        - perl --version
        - make -C bindings clean-perl configure-perl build-perl test-perl
        - make -C bindings clean-perl && make clean
        - make -C bindings cpan && tar xzf bindings/Crypt-RHash-[0-9]*.tar.gz
        - cd Crypt-RHash-[0-9]*/ && perl Makefile.PL && make all test

    - name: "Bindings: PHP"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: false
      addons:
        apt:
          packages:
            - php-dev
      script:
        - ./configure
        - make lib-shared test-lib print-info || ! cat config.mak librhash/config.mak config.log
        - php --version
        - make -C bindings configure-php build-php test-php
        - make -C bindings clean-php

    - name: "Bindings: Python"
      os: linux
      dist: xenial
      sudo: false
      script:
        - ./configure
        - make lib-shared test-lib print-info || ! cat config.mak librhash/config.mak config.log
        - python2 --version && python3 --version
        - PYTHON=python2 LD_LIBRARY_PATH=$(pwd)/librhash make -C bindings test-python
        - PYTHON=python3 LD_LIBRARY_PATH=$(pwd)/librhash make -C bindings test-python
        - make -C bindings clean-python

    - name: "Bindings: Ruby"
      os: linux
      dist: xenial
      compiler: gcc
      sudo: false
      env:
        - LIBRHASH_INC=-I$(pwd)/librhash
        - LIBRHASH_LD=-L$(pwd)/librhash
      addons:
        apt:
          packages:
            - ruby ruby-dev
      script:
        - ./configure
        - make lib-shared test-lib print-info || ! cat config.mak librhash/config.mak config.log
        - ruby --version
        - LD_LIBRARY_PATH=$(pwd)/librhash make -C bindings configure-ruby build-ruby test-ruby
        - make -C bindings clean-ruby
